### ISSUE TITLE
collection.find()

### ISSUE THREAD

**Issue by sonyarouje** [sergeyksv/tingodb#103]
Hi,
  I was doing some experiments with raspberrypi, initially i was using orientdb and seems like its heavy for my application. So decided to use Tingodb instead. Everything is working as expected and thanks for this light weight database.

I come across an issue while doing find() in collection. I am sure I am doing something wrong, so decided to check with you creators what's wrong I am doing. Below is my code.

Note: findOne() is returning result as expected.

`var Db = require('tingodb')().Db;
var group={
    command: 'MTOFF',
    firsTimeActivated:0,
    serialNumber:'0013a200407a25c1',
    timeout: 2,
    groupItems:[
        {
            serialNumber: '0013a200407a25c1',
            startCmd: 'SWHL',
            finishCmd: 'SWHH',
            currentIssuedCmd: ''
        },
        {
            serialNumber: '0013a200407a25ab',
            startCmd: 'SWHL',
            finishCmd: 'SWHH',
            currentIssuedCmd: ''
        }
    ]
}

var db = new Db('./db', {});
var collection = db.collection("Group");
// I did an insert of group object using the below code.
/*
collection.insert(group, function(err, doc){
    if(err)
       console.log(err); 
 });
*/
collection.find({serialNumber:'0013a200407a25c1'}, function(err, item) {
    console.log(item);
})`

I was expecting an array of group object. Instead I am getting the below result.

{ INIT: 0,
  OPEN: 1,
  CLOSED: 2,
  GET_MORE: 3,
  _query: { serialNumber: '0013a200407a25c1' },
  _c:
   { _tdb:
      { _gopts: {},
        _path: '/home/pi/tingodbtest/db',
        _cols: [Object],
        _name: 'db',
        _stype: 'fs',
        openCalled: false,
        ObjectID: [Object],
        Code: [Function: Code],
        Binary: [Object],
        Finder: [Object] },
     _name: 'Group',
     _store: {},
     _fd: null,
     _fsize: null,
     _id: 1,
     _wq:
      { limit: 100,
        _rc: 0,
        _q: [],
        _blocked: false,
        _stoped: false,
        _tc: -1,
        first: [Function] },
     _tq:
      { limit: 100,
        _rc: 0,
        _q: [],
        _blocked: false,
        _stoped: false,
        _tc: -1,
        first: [Function] },
     _idx: { '_id,1': [Index _id_] },
     _cache: { _tdb: [Object], size: 1000, _cache: [Object] },
     _mc: {},
     _check1: 97.25374029856175,
     collectionName: 'Group',
     init: [Function],
     _put: [Function],
     _get: [Function],
     _cmaxobj: 1024,
     _filename: '/home/pi/tingodbtest/db/Group' },
  _i: 0,
  _skip: 0,
  _limit: null,
  _count: null,
  _items: null,
  _sort: null,
  _hint: undefined,
  _arFields: {},
  _fieldsType: null,
  _fieldsExcludeId: false,
  _fields: {},
  timeout: true }

It will be very helpful if some one could help me to fix the issue, so that the find() query should return an array of Group object.

**Comment by sonyarouje** [comment]
I think I fixed the issue, I used find(filter).toArray() as shown below.

collection.find({serialNumber:'0013a200407a25c1'}).toArray(function(err, item) {
    if(err)
      console.log(err);
    else{
       console.log(item);
        }
    }
});

**Comment by sergeyksv** [comment]
You are right. Find return cursor. Cursor has some methods to access actual data. See here: https://mongodb.github.io/node-mongodb-native/api-generated/cursor.html
