### ISSUE TITLE
not running in strict mode

### ISSUE THREAD

**Issue by jbaron** [sergeyksv/tingodb#105]
Due to wanting to enable certain features, I'm running my JS application in strict mode (nodejs environment). However it turns out that I cannot use tingodb since it violates strict mode. For example it uses "with" keyword, which is not allowed in strict mode:

node_modules/tingodb/lib/tcoll.js:1134
				with (value.scope) {
				^^^^

Are there any plans to make tingodb "strict mode compliant" ?

**Comment by sergeyksv** [comment]
There is no such plans. But I'm curious what features are dependant from that? Especially switched on for external modules. You can easily enable it for your files, but how this is related to external modules?

**Comment by jbaron** [comment]
I am running node in strict mode (so with the --use-strict flag). That way I can use ES6 constructs like Classes and de-structuring natively (actually using Typescript with ES6 as target mode). However as a side effect, also all external loaded modules are checked for the "use strict" rules. 

Instead of running the whole application in strict mode I can indeed always include a "use strict" per individual file/module and remove the global flag. It is just that I also have some external TypeScript files that I also have to change (but a simple script can automate that).

Thanks for the quick response, so this issue/question can be closed.

**Comment by sergeyksv** [comment]
I not against making code compatible with strict mode but I not sure how we can replace things like with() which is essential for map reduce.

**Comment by jbaron** [comment]
Just from my basic understanding of MongoDB mapreduce capabilities, I
thought these were always functions (as opposed to arbitrary pieces of
code). So you could do someting like:

      var mapFunction1 = function() {  emit(this.cust_id, this.price); };

And then when you call it, since they are functions you could use the call
method:

     mapFunction1.call(doc, ...);

So pass the document as "this" context so that "this.cust_id" gets resolved,

But I'm sure I'm oversimplifying things, so this might not be applicable.
