### ISSUE TITLE
Search in array stop if empty item

### ISSUE THREAD

**Issue by vapkse** [sergeyksv/tingodb#109]
Hello.

First, thank you for tingodb.

Just one issue in my case, I have a data structure like this (simplified)
`
{
    "_id": {
        "$wrap": "$oid",
        "v": 2
    },
    "name": "10FD12",
    "vh1": 19,
    "ih1": 0.1,
    "units": [
        {},
        {},
        {
            "vamax": 250,
            "vg2max": 250,
            "vhkmax": 100,
            "pamax": 2.25,
            "pg2max": 0.45,
            "ikmax": 16.5,
            "cgk": 5,
            "cak": 5.2,
            "cga": 0.0025
        }
    ]
}
`

The units field is an array with 3 items, but first and second items are empties. 

If I search for vamax=250V for example, I found Nothing because the line 727 of finder,js return null in all cases. If I modify the function steep in finder.js like this, I found my record:

`
        function steep(ps, path, i, inarray) {
            ps+="['"+path[i]+"']";
            if (path.length==i)
                return "";
            i++;
            var s = "";
            s+= "v"+i+"="+ps+"\n";
727>>>          s+= "if (!v"+i+")"+ (inarray ? "continue" : "return null") + ";\n"
            if (path.length!=i) {
                s+= "if (Array.isArray(v"+i+")) {\n";
                s+= "for (i"+i+"=0; i"+i+"<v"+i+".length; i"+i+"++) {\n";
                s+= steep("v"+i+"[i"+i+"]",path,i, true);
                s+= "}\n}\nelse\n{\n";
                s+= steep("v"+i,path,i);
                s+= "}\n"
            } else
                s+= "res.push(v"+i+".valueOf())\n";
            return s;
        };
`

Just return continue in case of array and null in all other cases.
What do you think?

Best regards
Serge

**Comment by sergeyksv** [comment]
This should work pretty well if you enable search in array option (it is switched off by default). Can you check if you enabled this option?

**Comment by vapkse** [comment]
Just try, with the option and without, my records can't be found without my modification of the finder.

**Comment by sergeyksv** [comment]
It is hard to recreate context from text messages. I will appreciate if you create pull request at least with test that reproduce (your fix in pull request is also welcome). Please check https://github.com/sergeyksv/tingodb#submitting-bugs. This should be relatively easy, there is many examples in https://github.com/sergeyksv/tingodb/blob/master/test/misc-test.js
