### ISSUE TITLE
Using tingodb and mongodb simultaneously using mongoose? 

### ISSUE THREAD

**Issue by ElderOrb** [sergeyksv/tingodb#111]
Is it possible to use several instances of tingodb or tingo + mongo via mongoose? For example for implementing import from mongo to tingo and vice versa.

**Comment by sergeyksv** [comment]
There is no dedicated mechanism to switch between drivers. But It might be possible that you can try to rule this out by redefining global.MONGOOSE_DRIVER_PATH back and force (see here https://github.com/sergeyksv/tungus/blob/master/index.js)

**Comment by sergeyksv** [comment]
What will definitely work is separating this to different processes and using cluster and interprocess communication.

**Comment by ElderOrb** [comment]
> But It might be possible that you can try to rule this out by redefining global.MONGOOSE_DRIVER_PATH back and force

But will it help to get two drivers working in parallel simultaneously? Anyway, this looks like something I need to try, thank you!

> What will definitely work is separating this to different processes and using cluster and interprocess communication.

Sure, but I'd like to keep things simple.

**Comment by ElderOrb** [comment]
A bit ugly, but the following code did the trick: 

var decache = require('decache');
decache('tungus')
decache('mongoose')
delete global.MONGOOSE_DRIVER_PATH

Now I can have both tingo mongoose models and mongo mongoose models.
