### ISSUE TITLE
Ensuring correct interpretation of API calls

### ISSUE THREAD

**Issue by colinbes** [sergeyksv/tingodb#116]
Besides looking at source code is their any API documentation even in basic form explaining API calls.

I know many calls are based on mongo api so these are not too much of an issue, but I want to make sure I am using database.compactDatabase correctly.

From source code, I see that this function steps through collections and compacts each collection in turn but I am not sure on use of callback and how it works.

In calling db.compactDatabase(function(d) {...}), is 'd' an error object? Does it called once on error or multiple times?

What happens on error, does function stop or continue stepping through collections?

Great to see how this project has progressed - kudos to authors!

**Comment by sergeyksv** [comment]
I do believe there is some non formal standard for callbacks in nodejs and we follow it. Callback always called once to signal success or error. If it was called on error first callback arguments will be instance of Error class. Compact itself is designed to be safe (keep data in non corrupted state). In worst case it just will do nothing (like if there was not enough space).

**Comment by colinbes** [comment]
Thanks, all good to know—makes sense.
