### ISSUE TITLE
dependency package 'bson@0.2.x' blocks from upgrading to node4 or node6

### ISSUE THREAD

**Issue by osher** [sergeyksv/tingodb#127]
this version uses natively compiled modules, which fix you on node v0.x

Can you please consider upgrade it?

**Comment by sergeyksv** [comment]
Do you mind to submit pull request ?

**Comment by osher** [comment]
I tried, I got trouble:
https://github.com/sergeyksv/tingodb/pull/128
#128 

If all tests passed - it would have been a non-issue, but I don't have the capacity now to get into your code, and will have to work without tingo

**Comment by carlosfaria94** [comment]
I have the same problem here. In Node 6.9 it's impossible to proceed.

npm info lifecycle bson@0.2.22~install: bson@0.2.22
> bson@0.2.22 install /usr/src/app/node_modules/tingodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)
