### ISSUE TITLE
How can i disconnect from a tingo database and close the open database file?

### ISSUE THREAD

**Issue by lutzer** [sergeyksv/tingodb#133]
Hey,

I have a file open leak in my app, which is using tingodb and i was wondering how to prevent it?

This is how my app is organized:
```javascript
# database.js file manages the connection to the database
var Tingodb = require('tingodb')();

var Database = function() {
	//saves the data
	var db = new Tingodb.Db("data/", {});
	this.questions = db.collection("questions.db");
}

Database.prototype.questions = function() {
	return this.questions;
};

module.exports = Database;
```
```javascript
# question.js data model 
var Database = require('database');

var Question = {

	create : function(data,callback) {
		var db = new Database();
		...
		db.questions.insert(data,callback)
	},

	get : function(id,callback) {

		var db = new Database();
		db.questions.findOne({ _id : id }, callback);
	},

	remove : function(id,callback) {
		var db = new Database();
		db.questions.remove({_id: id},callback);
	},


}

module.exports = Question;
```

in my app i would just fetch data like this:

```javascript
var questions = require('questions');
questions.get(1,(err, doc) => {
  if (err) {
    log("error")
    return;
  }
  ...
});
```

But strangely whenever i open a data connection, the file doesnt seem to close. When i am checking the open file connection with `lsof`, file connections will accumulate rapidly… is there any command to close a database connection?

**Comment by sergeyksv** [comment]
db has .close method and it does what it should (shutdown everything). As a side note, it is uncommon to create new db instance every time you want to query something. This is true both for BIG MongoDB and for TingoDB especially (every time you open db it does full scan of files).
