### ISSUE TITLE
Find in array

### ISSUE THREAD

**Issue by Daaru00** [sergeyksv/tingodb#135]
Maybe I did not understand very well the _tiarr option.
My data structure is: 
```json
{
  "_id": 1,
  "date": "",
  "total": 25,
  "rows": [
    {
      "product": {
        "_id": 4,
        "name": "test"
      },
      "qty": 2,
    },
    {
      "product": {
        "_id": 5,
        "name": "test2"
      },
      "qty": 6,
    }
  ]
}
```
I want to search all document that have a determined product in rows property.

I try to do:
```javascript
db.collection("sales").find({
    "rows.product._id": 5
}, {}).toArray(function(err, data){
    if(err) console.error(err);
    else console.log(data);
})

db.collection("sales").find({
    "rows.product._id": 5
}, {"_tiarr": true}).toArray(function(err, data){
    if(err) console.error(err);
    else console.log(data);
})

db.collection("sales").find({
    "rows.product._id": 5
}, {"_tiar.rows.product": 0}).toArray(function(err, data){
    if(err) console.error(err);
    else console.log(data);
})

db.collection("sales").find({
    "rows.product._id": 5
}, {"_tiar.rows": 0}).toArray(function(err, data){
    if(err) console.error(err);
    else console.log(data);
})

db.collection("sales").find({
    "rows": {$elemMatch: {"product._id": 5}}
}, {}).toArray(function(err, data){
    if(err) console.error(err);
    else console.log(data);
})

db.collection("sales").find({
    "rows": {$elemMatch: {"product._id": 5}}
}, {"_tiar.rows": 0}).toArray(function(err, data){
    if(err) console.error(err);
    else console.log(data);
})

db.collection("sales").find({
    "rows.product._id": {$elemMatch: {"product._id": 5}}
}, {"_tiar.rows.product": 0}).toArray(function(err, data){
    if(err) console.error(err);
    else console.log(data);
})
```
but every attempt return an empty array. 
I'm doing somethings wrong? What's the correct method?

**Comment by sergeyksv** [comment]
Simple method is to enable search in array globally, this with `var Db = require('tingodb')(
{searchInArray:true}).Db`. 
Enabling this for individual queries / index worth it only if you want to have better performance but it is little bit tricky. So you need to know if you use index for that field or not. If you use index then you need to enable this on index creation. If not right on query. I not sure from your example if use use indexes or not.
If you not use index use `{"_tiar.rows.product._id": 0}. You can fine more usage pattern here: https://github.com/sergeyksv/tingodb/blob/master/test/search-array-test.js

**Comment by Daaru00** [comment]
I'm sorry, I noticed I had an older version, upgrading to the latest version everything works, I'll close the issue.
Thanks for this spectacular module, rapid and simple, I'm using into an [Electron](http://electron.atom.io/) application and switching from local to remote source is the top.
