### ISSUE TITLE
Unexpected identifier when querying $in with strings that have ['] character

### ISSUE THREAD

**Issue by diogoduailibe** [sergeyksv/tingodb#137]
Hi,

I'm using TingoDB version 0.4.2, downloaded from npm and when i'm querying a String with ['] character, an exception has been raised (SyntaxError: Unexpected identifier). 
For example, when i run this query: 

{"serie":
       {"$in":["Marvel's Agents of S.H.I.E.L.D"]}
}

I get the following stack trace:

SyntaxError: Unexpected identifier
    at tcoll.__find (.../node_modules/tingodb/lib/tcoll.js:1083:83)
    at .../node_modules/tingodb/lib/tcoll.js:1126:8
    at wqueue._exec (.../node_modules/tingodb/lib/wqueue.js:36:3)
    at .../node_modules/tingodb/lib/wqueue.js:32:9
    at .../node_modules/tingodb/node_modules/safe/lib/safe.js:332:13
    at task (.../node_modules/tingodb/node_modules/safe/lib/safe.js:642:8)
    at .../node_modules/tingodb/node_modules/safe/lib/safe.js:656:8
    at .../node_modules/tingodb/node_modules/safe/lib/safe.js:342:13
    at .../node_modules/tingodb/lib/tcoll.js:174:4
    at _fnApply (.../node_modules/tingodb/node_modules/safe/lib/safe.js:173:22)

Any string with normal characters works fine.

**Comment by sergeyksv** [comment]
@diogoduailibe Want to make npm update and put you into contributors list. Do you mind to give me your e-mail and name/nick. Thanks.

**Comment by diogoduailibe** [comment]
Hi @sergeyksv, 

my info:
e-mail: diogo.duailibe.silva@gmail.com
name: Diogo Duailibe
nick: diogoduailibe

Thank's!
