### ISSUE TITLE
Using count does not work as specified in the MongoDB API

### ISSUE THREAD

**Issue by Fohlen** [sergeyksv/tingodb#144]
Using the following simple code does give me some weird results:

```js
var Engine = require('tingodb')();
var db = new Engine.Db('somedirectorypath', {})

let items = database.collection('items');
items.insert({a: 1})
items.insert({b: 2})
items.count() // Bummer. this won't even let me count
```

According to the MongoDB API this should just working fine..
https://docs.mongodb.com/manual/reference/method/db.collection.count/#examples
What MongoDB API is being used here? Any hint's whats wrong?

**Comment by sergeyksv** [comment]
Mongo has so called mongo shell which is JS based but this is not the same as NodeJS API. Please use this documentation as reference https://mongodb.github.io/node-mongodb-native/contents.html

**Comment by Fohlen** [comment]
Thanks for the quick reaction though! The website is linking to the Mongo Shell in the first place, it'd be good for newcomers to have this link instead. Maybe updating the website would be nice 👍
