### ISSUE TITLE
IDEA: A new GUI manager for TingoDB for local projects only. Visit: 'https://github.com/Himujjal/tingo-db-gui-manager'

### ISSUE THREAD

**Issue by Himujjal** [sergeyksv/tingodb#157]
I am currently working on a new GUI for TingoDB and MongoDB using tungus and Mongoose. If any contributor is willing to work towards it then feel free. Here is the link to the repo:

[https://github.com/Himujjal/tingo-db-gui-manager](https://github.com/Himujjal/tingo-db-gui-manager)

I am using React for front-end.

**Comment by SridharRamasami** [comment]
Hi,

I am getting the below error when I try to install and run:

> server@1.0.0 dev /home/lsm/tingo-db-gui-manager/server
> nodemon --watch src --ignore src/models/ --ignore src/db/ --exec "cls && node src/index.js"

[nodemon] 1.12.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /home/lsm/tingo-db-gui-manager/server/src/**/*
[nodemon] starting `cls && node src/index.js`
sh: 1: cls: not found
[nodemon] failed to start process, "cls && node src/index.js" exec not found
events.js:187
      throw err;
      ^

Error: Unhandled "error" event. (127)
    at Bus.emit (events.js:185:19)
    at ChildProcess.<anonymous> (/home/lsm/tingo-db-gui-manager/server/node_modules/nodemon/lib/monitor/run.js:128:11)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@1.0.0 dev: `nodemon --watch src --ignore src/models/ --ignore src/db/ --exec "cls && node src/index.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lsm/.npm/_logs/2017-12-13T08_10_49_439Z-debug.log

Where should I look?  What should I do?
Sridhar

**Comment by Himujjal** [comment]
I did not quite make it cross platform. Only windows supported. I need to make a few changes before i can do something about it.
