### ISSUE TITLE
Documentation: Mongo API version?

### ISSUE THREAD

**Issue by apowers313** [sergeyksv/tingodb#162]
The Tingo documentation says that ["The rest is plain MongoDB API"](http://www.tingodb.com/info/) and links to the [MongoDB API](http://mongodb.github.io/node-mongodb-native/); however, it's not clear what version of the API it is referring to... 2.2? 3.0?

After reading the MongoDB API, [insert is deprecated](http://mongodb.github.io/node-mongodb-native/3.0/api/Collection.html#insert) so I used [insertOne](http://mongodb.github.io/node-mongodb-native/3.0/api/Collection.html#insertOne) as recommended by the MongoDB docs. Unfortunately, it seems like TingoDB doesn't implement `insertOne`?

Hopefully a quick fix to this is just changing the link and documentation to point to the correct version of the MongoDB API.

**Comment by apowers313** [comment]
Actually, this is probably related to #160 as well.

**Comment by sergeyksv** [comment]
API is strictly compatible to 1.4.x. 2.x and above are not fully supported. The reality is that 2.x was very poorly handled by MongoDB NodeJS driver maintainers when like 2.0.37 might break compatibility with 2.0.36 so we just have no any motivation to keep that strange API breakage game. Keep in mind that this is not related to MongoDB version, 1.4.x driver can work up to MongoDB 3.4.

**Comment by apowers313** [comment]
Very helpful, thanks!

Can you change the link [here](http://www.tingodb.com/info/) to read "MongoDB API (version 1.4.x)" and change the link to this page: http://mongodb.github.io/node-mongodb-native/1.4/ . Or let me know if there's some way that I can submit a PR to do the same?

**Comment by sergeyksv** [comment]
@apowers313 Clone, make a change, submit PR. Thanks!

**Comment by apowers313** [comment]
Is the website in a GitHub repo somewhere?
