### ISSUE TITLE
value in finder.js logs warning for valid value

### ISSUE THREAD

**Issue by blloyd75** [sergeyksv/tingodb#37]
@ line 749 of finder.js, which was
	else
		console.log("WARNING: Using unrecognized value in query",v)

should instead read
	else if (this.v !== null)
		console.log("WARNING: Using unrecognized value in query",v)

Alternately, this.v === null could be added as an or for the first if condition.

Passing a value as null does work, and is required for some circumstances, particularly searches for unset values.  Previously doing so caused log messages warning of the "unrecognized" value.

**Comment by blloyd75** [comment]
```
"use strict";
process.title = 'tingo-null-test';

var fs = require('fs');

// TINGO DB (MongoDb clone in JavaScript)
var tingo = require("tingodb");
var dbengine = tingo();
if (!fs.existsSync('tingostore'))
    fs.mkdirSync('tingostore');
if (fs.existsSync('tingostore/teststore'))
    fs.unlinkSync('tingostore/teststore');

var db = new dbengine.Db('tingostore', {});

// Database collections
var collection = db.collection('teststore');

var tosave = [];
tosave.push({nullable:null, value:'dumb 1'});
tosave.push({nullable:null, value:'dumb 2'});
tosave.push({nullable:null, value:'dumb 3'});
tosave.push({value:'dumb 4'});
tosave.push({value:'dumb 5'});

var testsave = function() {
    if (tosave.length > 0) {
        var save = tosave[0];
        tosave.splice(0,1);
        console.log("SAVING " + JSON.stringify(save));
        collection.save(save, {w:1}, testsave);
    }
    else
        testselect({}, function() {testselect({nullable:null}, testupdate1);});
};

var testselect = function(query, nextroutine) {
    collection.find(query).toArray(function(err, arr) {
        console.log("QUERY RESULTS");
        arr = arr || [];
        for (var i=0; i<arr.length; ++i)
            console.log("   " + JSON.stringify(arr[i]));
        console.log("END QUERY RESULTS");
        if (typeof nextroutine==='function') nextroutine();
    });
};

var testupdate1 = function() {
    console.log("UPDATING nullable for 'dumb 1' to 1");
    collection.update({value:'dumb 1'}, {$set: {nullable:1}}, {w:1}, 
        function() {testselect({}, function() {testselect({nullable:null}, testupdate2);})});
};

var testupdate2 = function() {
    console.log("UPDATING null nullable to 2");
    collection.update({nullable:null}, {$set: {nullable:2}}, {w:1, multi:true}, 
        function() {testselect({}, function() {testselect({nullable:null}, function() {console.log("Test Complete");});})});
};

// Start test sequence
testsave();

```

**Comment by slang800** [comment]
I just ran into the same problem with searching for a field that is null:

```coffeescript
collection.find(
  {
    attachedLink: {$ne: null}
    attachedLinkExpanded: null
  }
  cb
)
```

Btw, @blloyd75: you can use triple backticks to surround your code & get syntax highlighting - https://guides.github.com/features/mastering-markdown/

**Comment by sergeyksv** [comment]
Seems to be fixed

**Comment by slang800** [comment]
That second issue @blloyd75 mentioned (about how a search for null was/is wrong) might still be broken. I haven't tested it, but from the docs this is the behaviour:

>The `{ cancelDate : null }` query matches documents that either contain the `cancelDate` field whose value is `null` or that do not contain the `cancelDate` field. If the queried index is sparse, however, then the query will only match `null` values, not missing fields.

> _Changed in version 2.6_: If using the sparse index results in an incomplete result, MongoDB will not use the index unless a `hint()` explicitly specifies the index.

...it's a pretty weird behaviour, so we should prolly open a separate issue & add some tests for it
