### ISSUE TITLE
findAndModify() needs to return the updated record, not the old one

### ISSUE THREAD

**Issue by mercmobily** [sergeyksv/tingodb#40]
The call `findAndModify()` needs to return the actual record, rather than the version of the record before modifications.
This simple script shows exactly the problem:

    var Db = require('tingodb')().Db;
    var db = new Db('/tmp/tests', {});
    var collection = db.collection( 'addresses' );

    a = {
      personId: 555,
      street  : 'bitton',
      city    : 'perth',
      id      : 12345
    };

    console.log("Removing...");
    collection.remove( {}, function( err ){
      if( err ) return process.exit( err );

      console.log("Inserting...");
      collection.insert( a, function( err ){

        if( err ) return process.exit( err );

        console.log("Finding...");
        collection.findAndModify( { '$and': [ { id: 12345 } ] }, {}, { $set: { street: 'bitton CHANGED', __uc__street: 'BITTON CHANGED' }, $unset: {} } , function( err, d ){

          console.log( err );
          if( err ) return process.exit( err );

          console.log("RETURNED:", d );

          collection.find( {} ).toArray( function( err, res ){
            if( err ) return process.exit( err );

            console.log("Results:", res);

          });
        });
      });
    });

**Comment by sergeyksv** [comment]
According to http://mongodb.github.io/node-mongodb-native/api-generated/collection.html#findandmodify it should return version prior modification. If you want version after modifications use new option. It should be supported.

**Comment by mercmobily** [comment]
My apologies Serge!
