### ISSUE TITLE
Updating one element in a nested arrays says it worked, but it didn't

### ISSUE THREAD

**Issue by mercmobily** [sergeyksv/tingodb#63]
Hi,

create a DB instance like this (remember the `searchInArray` option!)

    db = new (require('tingodb')({ searchInArray: true } ).Db)('/tmp/tests', {} );

Imagine you have a record like this:
   
````Javascript
p = { id: 5907030,
    name: 'Tony',
    surname: 'Mobily',
    age: 38,
    configId: 7808790,
    __uc__name: 'TONY',
    __uc__surname: 'MOBILY',
    _children: 
     { addressesR: 
        [ { id: 3076154,
            personId: 5907030,
            configId: 7808790,
            street: 'bitton',
            city: 'perth',
            __uc__street: 'BITTON',
            __uc__city: 'PERTH',
            _children: {} },
          { id: 5544211,
            personId: 5907030,
            street: 'samson',
            city: 'perth',
            __uc__street: 'SAMSON',
            __uc__city: 'PERTH',
            _children: {} } ],
       configId: 
        { id: 7808790,
          configField: 'C1 - Config Field',
          configValue: 'C1 - Config Value',
          __uc__configField: 'C1 - CONFIG FIELD',
          __uc__configValue: 'C1 - CONFIG VALUE',
          _children: {} } },
    _id: 122,
    _clean: true,
    position: 100 }
````

Add the item to the database:

    db.collection('fails').insert( p );

Now check that the record is there:

    db.collection('fails').find({}).toArray( function( e, a ){ console.log(require('util').inspect( a, { depth: 10 }  ) ); } )

Now run an update on it, using the `$` operator:

    db.collection('fails').update( { '_children.addressesR.id': 3076154, _clean: true }, { '$set': { '_children.addressesR.$.street': 'bitton CHANGED', '_children.addressesR.$.__uc__street': 'BITTON CHANGED' },'$unset': {} }, function( e, r ){ console.log( e, r ); } );

It returns `null, 1` (no error, one item changed). However, the record hasn't changed:

    db.collection('fails').find({}).toArray( function( e, a ){ console.log(require('util').inspect( a, { depth: 10 }  ) ); } ) 

This is one of the bugs that makes SimpleDbLayer's tests fail when using TingoDb. I plan on adding more detailed reports here -- hopefully, if you have time to push this further, it will eventually pass all tests!

Thanks,

Merc.

**Comment by mercmobily** [comment]
After having a loser look, it really looks like this is the _only_ issue preventing me from passing all tests... which is amazing! Thank you for your great work.

**Comment by sergeyksv** [comment]
Yep, positional operator is not supported now. Its kind of top priorit for my spare time.

**Comment by mercmobily** [comment]
Is there another ticket for it? Is that why you closed it?

**Comment by sergeyksv** [comment]
Another one is #41
