### ISSUE TITLE
On OS X, .DS_Store file can cause db.collections() to fail

### ISSUE THREAD

**Issue by akumpf** [sergeyksv/tingodb#68]
If I preview the database's folder with Finder on OS X, a hidden file called ```.DS_Store``` is placed in the directory (annoying, I know).

Then if I try to use the ```db.collections()``` functions, I get the error: "collection names must not start or end with '." because it sees the ```.DS_Store``` file.  This makes sense, but it's a bummer. 

Perhaps Tingo could ignore system files starting with a period instead of failing with the error? Windows does something similar with ```Thumbs.db```, but because it doesn't start with a period I think it won't totally gum up the works.

Cheers,
Adam

**Comment by akumpf** [comment]
More specifically, I'm thinking ```db.collectionNames()``` should disregard files that start with a period, near here: https://github.com/sergeyksv/tingodb/blob/master/lib/tdb.js#L111

**Comment by louwers** [comment]
A pretty radical temporary fix: https://www.aorensoftware.com/blog/2011/12/24/death-to-ds_store/.
Works for 10.6-10.10.
