### ISSUE TITLE
Using tingodb in-memory store in unit-tests

### ISSUE THREAD

**Issue by hellboy81** [sergeyksv/tingodb#69]
Написаны юнит тесты, которые работают на локальной машине. Все они зеленые.
Пытаюсь использовать актуальную версию `tingodb` для тестирования с in-memory базой.

Файл спецификаций mocha:

require часть:
```js
tingo      = require('tingodb')({memStore: true, nativeObjectID: true}) // with nativeObjectID : false the same problem
```

before часть:
```js
db = new tingo.Db('testdb', {});

db.open(function (err, db) {
// Initialize standard modules used by SUT
            sut = myMod.init(db, ...)

            done()
        })
```

before each часть:

```js
var dummyData = [..]
async.each(dummyData, function (item, cb) {
            db.collection(myTestId).insert(item, cb)
        }, done)
```

afterEach часть:
```js
db.collection(userId).drop(done)
````

Ошибка: не проходят тесты, которые обращаются к базе.
Такое ощущение, что в базе просто нет данных.

Еще один вероятный источник ошибок  (не проверялся):

В `beforeEach` происходит инициализация мокированной файловой системы (`mockFs`), в `afterEach` - восстановление.

Использование `mockFs` никакого влияния на прохожение юнит-тестов с реальной базой `Mongo` не оказывает.

**Comment by sergeyksv** [comment]
Проблема только если memStore:true или вообще с tingodb?

**Comment by hellboy81** [comment]
Я пока пробовал реально только `memstore`.

Конкретный пример (отлаживаю `mocha` тест при помощи `node-debugger`):

```js
db.collection(myTestId).findOne({
            <Условия>
        }, function (err, item) { // err=null, item=null
 ````

Дамп db:
```
gdb
    Binary: function Binary(buffer, subType) {
    Code: function Code(code, scope) {
    Finder: Object
    ObjectID: function ObjectID(id) {
    _cols: Object
    _gopts: Object
    _mstore: Object
    _name: "testdb"
    _path: "/home/local/.../node/trunk/myproject/testdb"
    _stype: "mem"
    __proto__: gdb
```

Можно ли из консоли отладки Chrome выполнить синхронные команды, котзорые позволяют хотя бы узнать, пуста ли база?

**Comment by sergeyksv** [comment]
В случае с memStore:true вcе данные в _mstore. Если на диске то в отдельных файликах по пути _path. Мне сложно судить не видя код, но если прямо все не работает это две причины, что то не так с инициализацией или с асиндронности. По традиции, в т.ч. в тестах mongo db там любят шарашить команды не дожидаясь результата. Так в самом проекте очень много тестов (>600) и все прекрасно работают как c mongodb так и tingodb.

**Comment by hellboy81** [comment]
Проблема локализована: `count` документов в колбеке beforeEach все еще равно равно нулю 
```js
async.each(dummyData, function (item, cb) {
            db.collection(userId).insert(item, cb)
        }, myDone(done))
```

где myDone - моя тестовая функция:

```js
var myDone = function(done) {
            db.collection(userId).count(function(err, count){ count.should.above(0); done()}) // failed
        }
```

Какой  должен быть правильным код заполнения тестовыми данными, чтобы он правильно работал как для Mongo так и для Tongo?

**Comment by sergeyksv** [comment]
Так как оно сейчас написано mydone выполняется еще до того как что то выполнится внутри цикла, естественно ничего еще нет внутри. Чтобы оно так рабтало myDone должна быть модифицирована как:
var myDone = function(done) {
            return function (err, done) { 
                 db.collection(userId).count(function(err, count){ count.should.above(0); done()}) 
            }
        }
Кроме этого не правильно проверять результат работы не проверив предаврительно наличие ошибки (err). Очень желательно это делать.

**Comment by hellboy81** [comment]
**Проблема решена**

В тестовых данных и в тестируемом модуле был использован `ObjectID` от `mongodb`
По всей видимости он был источником проблем.

Тесты заработали после того, как я заменил  везде ObjectId от монги на `tingo.ObjectID` (`nativeObjectID: true`).

Не совсем понятно, какой Id нужно использовать для тестов в памяти.

См. также комментарий к коммиту 85babd4f69656b811dbce201238310ae7f33d1af


> А с чего вы это взяли?

> `done()`, согласно [документации](https://github.com/caolan/async#each) выполняется всегда  после окончания `each`-цикла

> Проверил с `console.log`: `done` выводит последним.

> Пробовал обернуть в фунцкию (как вы предлагали) - тот же самый результат:

**Comment by sergeyksv** [comment]
Когда написано myDone(done) это уже вызов функции. Т.е. непосредственно в asynс.each вы уже передали результат ее работы (undefined в даннам случае так как сама done ничего не возвращает). То что и так и так работает как раз и означает что сделано не правильно. Добавте return true; в mydone. В правильном варианте это ни на что не повлияет. В неправильном напишет что то типа object is not a function. Это async.each попытается выполнить true()

**Comment by hellboy81** [comment]
Другой вопрос: согласно рекоментациям в юнит-тестах необходимо проверять не состояние базы данных после вызова метода, а то, что отповляется в базу.

Т.е. необходимо создать шпионм, который бы следил бы за методом.

Непонятно, как с помощью `sinon.js` создать шпиона, который бы следил за мотодом  коллекции.

Т.е. как мне отследить вызов метода  `db.collection(myColName).update(,)` ?

В примеров не нашел.

**Comment by sergeyksv** [comment]
Не могу помочь, я не разделяю такой подход и мы его не используем. На мой вгляд тестировать надо результат, но возможно не в базе, а как его видно через API приложения.

**Comment by hellboy81** [comment]
ОК, я тоже вначале так думал, но в случае `как его видно через API приложения` мы используем потенциально непротестированный код.

В любом случае большое спасибо за поддержку.

**Comment by hellboy81** [comment]
ОК, если целиком положиться на `sinon.js, то потребность в `tingodb` отпадает.

**Comment by sergeyksv** [comment]
:)
