### ISSUE TITLE
How to replace MongoDB by TingoDB in the Deployd project?

### ISSUE THREAD

**Issue by vpxavier** [sergeyksv/tingodb#71]
We want to use deployd on our homemade device running OpenWRT. As MongoDB would required too much memory, we want to use TingoDB in stead of MongoDB. How to configure Deployd (www.deployd.com) to do so? 
Thanks a lot!

**Comment by sergeyksv** [comment]
I'm not familiar with deployd so I not know. TingoDB is compatible on api level but it is not expose same network protocol. This means that some code changes (initialization of db connection) are required. For example of app with dual setup you can check this one - https://github.com/sergeyksv/skilap
