### ISSUE TITLE
Reset/drop database

### ISSUE THREAD

**Issue by Phoscur** [sergeyksv/tingodb#74]
How can I use this with TingoDB? (trying to use it as a PureJS fallback)
```javascript
/**
 * Reset database
 * @param {Function} callback
 */
db.destroy = function(callback) {
  this.command({dropDatabase:1}, callback);
};
```
I guess it means just removing the database file, would you consider this feature?

```
  this.command({dropDatabase:1}, callback);
       ^
TypeError: this.command is not a function
```

**Comment by sergeyksv** [comment]
There is standard collection.drop or db.dropCollection command. So I not sure what you looking for?

**Comment by Phoscur** [comment]
I'm loading for a full database reset , mostly for testing purposes!

**Comment by sergeyksv** [comment]
You can use this methods for testing purpose as well.

**Comment by Phoscur** [comment]
This is not solved, reseting the database is a common use case. 
I see three silutions:
a) TingoDB implements the command method, mirroring MongoDB 
b) I have to implement feature detection
c) I use dropCollection instead of dropDatabase, which seems error prone..

**Comment by sergeyksv** [comment]
TingoDB does not support wire protocol of MongoDB, it is compatible on api level only. There is db.dropDatabase function for your purpose.

**Comment by Phoscur** [comment]
With .dropDatabase I'm getting:
```
{ [Error: ENOENT: no such file or directory, scandir 'C:\Users\Phoscur\iagastro\
database']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\Phoscur\\iagastro\\database' }
```
Seems I can't drop a nonexistend database, but a warning should be enough?
With my previous implementation, MongoDB didn't care at all if there was something to drop.

**Comment by Phoscur** [comment]
Nevermind, reading documentation again, I created the needed folder (I was thinking TingoDB works like sqlite with a single file), now everything works fine.
