### ISSUE TITLE
When I remove a item, a blank line appears on file 

### ISSUE THREAD

**Issue by dieegorenan** [sergeyksv/tingodb#75]
After the removed item, a blank line appears on file collection. Is that normal?
Everything is working well, but I'm curious.

Thanks!

**Comment by dottodot** [comment]
I'm experiencing the same thing. Although everything works ok I'm concerning that over a long period of time the database file is going to become increasingly larger with deleted items taking up unnecessary space.

**Comment by sergeyksv** [comment]
To provide fail safe operations files are used in append only mode. Thus deletion is also a record in db. Actually every update add something to the file. To solve space overuse there is compactination features that will be triggered automatically when unused space ratio will be above some threshold. 
Going further append only files provide one more essential feature for almost zero price. Any search will provide results in some specific state of database, kind of snapshot. This is mimic mongodb behaviour but initially we though it will be very hard (resource expensive) to implement it.
