### ISSUE TITLE
Database Corrupted: Error during load - SyntaxError: Unexpected number

### ISSUE THREAD

**Issue by joelnet** [sergeyksv/tingodb#78]
Here's the stack trace:

	Error: sessions: Error during load - SyntaxError: Unexpected number
		at DataService.SetSession (C:\...\DataService.js:39:30)
		at C:\DEV\hack\node_modules\tingodb\lib\wqueue.js:30:12
		at _sure (C:\DEV\hack\node_modules\tingodb\node_modules\safe\lib\safe.js:297:21)
		at async.whilst (C:\DEV\hack\node_modules\tingodb\node_modules\async\lib\async.js:677:28)
		at tcoll.initFS.self.ensureIndex._id (C:\DEV\hack\node_modules\tingodb\lib\tcoll.js:121:15)
		at _catcher (C:\DEV\hack\node_modules\tingodb\node_modules\safe\lib\safe.js:243:4)
		at _sure (C:\DEV\hack\node_modules\tingodb\node_modules\safe\lib\safe.js:302:4)

Here's the code:

	sessions.update({ sid: model.sid }, model, { upsert: true }, function (err, result) {
        // ...
	});

This is at the end of the DB file:

	{"_id":10,"_uid":10,"_dt":1436233947932,"_s":"f48f6c49c4d5e2f73538a0dd9f214d49"}
	{"sid":"37dda08e-7791-4fee-99d6-c3ab9b9ed839","updatedAt":{"$wrap":"$date","v":1436233947931,"h":"2015-07-07T01:52:27.931Z"},"test":"success","_id":{"$wrap":"$oid","v":10}}
	{"k":"0000000080","o":"0000000172","v":"001"}
	{"_id":10,"_uid":10,"_dt":1436233948050,"_s":"4356cf1cab2fb61c32456c04cd82e417"}
	{"sid":"37dda08e-7791-4fee-99d6-c3ab9b9ed839","updatedAt":{"$wrap":"$date","v":1436233948049,"h":"2015-07-07T01:52:28.049Z"},"test":"success","_id":{"$wrap":"$oid","v":10}}
	00000184","v":"001"}
	{"_id":9,"_uid":9,"_dt":1436233947925,"_s":"8135a56e39a32b5981c25a70f37c07eb"}
	{"sid":"37dda08e-7791-4fee-99d6-c3ab9b9ed839","state":"shell","updatedAt":{"$wrap":"$date","v":1436233947923,"h":"2015-07-07T01:52:27.923Z"},"_id":{"$wrap":"$oid","v":9},"login":"wef"}
	{"k":"0000000078","o":"0000000184","v":"001"}
	{"_id":9,"_uid":9,"_dt":1436233948042,"_s":"acdce84228fb25209cab201c7601b51d"}
	{"sid":"37dda08e-7791-4fee-99d6-c3ab9b9ed839","state":"shell","updatedAt":{"$wrap":"$date","v":1436233948040,"h":"2015-07-07T01:52:28.040Z"},"_id":{"$wrap":"$oid","v":9},"login":"wef"}

There seems to be a mystery `00000184","v":"001"}` line thrown in there.

There was no shutdown or crash that caused this. All the writes to the db were done sequentially at about 5-10 writes a second.

I can regularly reproduce this.

**Comment by groovy354** [comment]
I'm also experiencing this issue :(

**Comment by sergeyksv** [comment]
Fixed now, latest partially saved object will be removed from db
