### ISSUE TITLE
Когда будет первый релиз???

### ISSUE THREAD

**Issue by LestaD** [sergeyksv/tingodb#79]
Если есть, сделайте на хабре релиз git tag

**Comment by sergeyksv** [comment]
Я не очень понял вопроса. Релизов было уже несколько. Биллиотека распространяется через https://www.npmjs.com/package/tingodb
Я что то упустил?

**Comment by LestaD** [comment]
@sergeyksv сделайте релиз на гитхабе. https://github.com/sergeyksv/tingodb/releases
`$ git tag 1.0.0`
`$ git push origin --tags`
