### ISSUE TITLE
Is there any API to remove duplicates from database file? 

### ISSUE THREAD

**Issue by ElderOrb** [sergeyksv/tingodb#81]
I'm asking because at the moment it is not very convenient to review db content using text viewer due to presence of duplicates (modified entries) so would be cool to get some API allowing to 'compact' db on demand. If there is no such an API are there any workarounds available?

**Comment by sergeyksv** [comment]
Compaction happening automatically on next db load when amount of wasted spaces grows above certain ratio. There is private Collection._compact function, though I not sure ho it will work without reopening database and collection.

**Comment by ElderOrb** [comment]
Ok, so Collection._compact + reopen should do the trick. What about 'tungus' API ? Is there any means how to achieve the same result using it?

**Comment by sergeyksv** [comment]
Added db.compactDatabase and collection.conpactCollection
