### ISSUE TITLE
escaped dots in tingodb not found through regex (mongodb works)

### ISSUE THREAD

**Issue by frederik** [sergeyksv/tingodb#84]
I found a weird nuance when searching with regular expressions that escape dots with double backslashes.

In mongodb I can use ^.$ and ^\.$ to find a simple .
In tingodb the same does not work. I attached a test to reproduce the issue. Whether or not it makes sense to escape with a double \, not sure.. there seems to be a different behaviour in mongodb here though. The test only fails when I run it with tingodb.

p.s.: for me this makes using the current keystonejs hard with tingodb, since they chose to use \. escapes for email addresses in the backend login.

see #83 for a failing test.

**Comment by markokocic** [comment]
I encountered the same issue when trying to use the latest version of KeystoneJS. 

See http://stackoverflow.com/questions/32266472/problems-running-keystonejs-without-mongodb/32271512#32271512 for more details.

It would be nice to be able to use KeystoneJS without having to patch its source code.

**Comment by frederik** [comment]
I have also brought this up in the keystonejs repo here on [gitter](https://gitter.im/keystonejs/keystone?at=55d9adf0a6bcd88940689047). Since this is working with mongodb though I'd reckon we should fix this in tingodb - I did not have the time yet to have a depper look at the tingodb source code in order to provide more than a failing test case.

p.s.: I am working on an update of the blogpost you referenced on stackoverflow (pending this fix ;-))
