### ISSUE TITLE
query returns empty when index is created

### ISSUE THREAD

**Issue by angelochen960** [sergeyksv/tingodb#88]
Hi,
following sample, I am expecting samples[2] got returned, but instead, it returns empty:
~~~
var samples = [
    {"date2": "2008-12-29T23:00:00.000Z", "n_length": 16},
    {"date2": "2009-12-29T23:00:00.000Z", "n_length": 5},
    {"date2": "2009-12-30T23:00:00.000Z", "n_length": 10},
    {"date2": "2009-12-28T23:00:00.000Z", "n_length": 11},
    {"date2": "2008-12-29T23:00:00.000Z", "n_length": 16},
    {"date2": "2008-12-29T23:00:00.000Z", "n_length": 16}
]

var Engine = require('tingodb')({memStore: true, searchInArray: false})

var db = new Engine.Db('test', {});

var collection = db.collection("batch_document_insert_collection_safe");

var q = {
    date2: {$gte: '2009-01-01T00:00:00.000Z', $lt: '2010-01-02T00:00:00.000Z'},
    n_length: {$gte: 8, $lte: 10}
}
collection.insert(samples, {w: 1}, function (err, result) {
    collection.createIndex({"date2": 1}, function (err, indexname) {
        collection.find(q).toArray(function (err, results) {
            console.log(results)
        })
    })
});
~~~
but if I remove the createIndex, it returns properly, why?
~~~
collection.insert(samples, {w: 1}, function (err, result) {
    //collection.createIndex({"date2": 1}, function (err, indexname) {
        collection.find(q).toArray(function (err, results) {
            console.log(results)
        })
    //})
});
~~~

**Comment by sergeyksv** [comment]
Just on first look it seems that it happens because you use date not as a date but as string. I'll appreciate if you create a test that reproduce this issue and submit it as merge request. See https://github.com/sergeyksv/tingodb#submiting-bugs for details. This way we can also check what is proper behaviour (how mongodb works).

**Comment by angelochen960** [comment]
some observations:
1) if query changed to following, it works:
~~~
 q = {
    date2: {$gte: '2009-01-01T00:00:00.000Z', $lt: '2010-01-02T00:00:00.000Z'}
}
~~~
2) I have tested similar code in mongodb and it works, but I can't come out a code as simple as the one in this post.

**Comment by angelochen960** [comment]
I have created a ranges-test.js for this case, it works with mongo, but not tingodb, it seems to me when two fields have ranges as query, that will have problem, if the second field is not a range, but $gte, it works too, pull request: https://github.com/sergeyksv/tingodb/pull/89

**Comment by sergeyksv** [comment]
Fixed. Will wait for Travis CI results ad will update npm after that.

**Comment by sergeyksv** [comment]
published

**Comment by angelochen960** [comment]
works, thanks.
