### ISSUE TITLE
tingodb+mongoose

### ISSUE THREAD

**Issue by wormen** [sergeyksv/tingodb#98]
подскажите, как я могу использовать вашу БД вместе с mongoose?
пробовал подключить как описано тут https://www.npmjs.com/package/tungus

собственно, как и от `tungus` я получаю ошибку

```
Error: Invalid mongodb uri. Must begin with "mongodb://"
  Received: tingodb://e:\node\pm2-manager\data
```
сначала грешил на виндовые пути, запустил в ubuntu, результат тот же самый

**Comment by sergeyksv** [comment]
Так как написано должно работать. Единственное условие Mongoos 3.x. Смотрите пример https://github.com/sergeyksv/tungus/blob/master/examples/population-basic.js

**Comment by wormen** [comment]
так актуальная версия mongoose 4.x
почему бы ПО не обновить? чтобы было совместимо

**Comment by sergeyksv** [comment]
Нет времени это раз. Второе в новых версиях mongodb драйвера все оченть путанно и вязко. Авторы NodeJS monogdb драйвера эээээ странные ребята и постоянно меняют api регулярно ломая совемстимость и делая другие пакости. Если интересно глянте код монгус, там целых две обертки пытаются разрулить эти пакости. Так что пока это не устаканится что то менять не хочется.
